# Generated by Django 5.0.1 on 2024-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attemps',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
