# Generated by Django 5.0.1 on 2024-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0003_transaction_attemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Cont blocat'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='unlock_pin',
            field=models.CharField(blank=True, max_length=120, verbose_name='PIN'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pin',
            field=models.CharField(blank=True, max_length=120, verbose_name='PIN'),
        ),
    ]
