# Generated by Django 5.0.1 on 2024-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0006_alter_trustcontact_trust_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='role',
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default='0752019203', max_length=120, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='funds',
            field=models.IntegerField(blank=True, default=5000, null=True),
        ),
    ]
