# Generated by Django 5.0.1 on 2024-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0007_remove_appuser_role_appuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='rsa_private',
            field=models.TextField(blank=True, verbose_name='RSA Private'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='rsa_public',
            field=models.TextField(blank=True, verbose_name='RSA Public'),
        ),
    ]
