# Generated by Django 5.0.1 on 2024-01-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0008_appuser_rsa_private_appuser_rsa_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pin',
            field=models.TextField(blank=True, verbose_name='PIN'),
        ),
    ]
